

/* Create Sequences */

CREATE SEQUENCE SEQ_ATTACH_SAVE_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BOOKMARK_BM_IDX NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BOOKMARK_BM_NO NOCACHE NOCYCLE;



/* Create Tables */

CREATE TABLE ATTACH
(
	NO number NOT NULL,
	SAVE_NO number DEFAULT 1 NOT NULL,
	A_LOCATION nvarchar2(100) NOT NULL,
	A_NAME nvarchar2(50) NOT NULL,
	A_EXTENSION varchar2(10) NOT NULL,
	PRIMARY KEY (NO, SAVE_NO)
);


CREATE TABLE BOARD
(
	NO number NOT NULL,
	ID varchar2(12) NOT NULL,
	TITLE nvarchar2(50) NOT NULL,
	CONTENT nvarchar2(1000) NOT NULL,
	HIT_COUNT number NOT NULL,
	BM_COUNT number NOT NULL,
	ATTACH_FLAG char NOT NULL,
	POST_DATE date DEFAULT SYSDATE NOT NULL,
	EDIT_DATE date DEFAULT NULL,
	DELETE_DATE date DEFAULT NULL,
	PRIMARY KEY (NO)
);


CREATE TABLE BOOKMARK
(
	BM_NO number NOT NULL,
	NO number NOT NULL,
	ID varchar2(12) NOT NULL,
	PRIMARY KEY (BM_NO)
);


CREATE TABLE INACTIVE
(
	ID varchar2(12) NOT NULL,
	INACTIVE_DATE date DEFAULT SYSDATE NOT NULL
);


CREATE TABLE MEMBER
(
	ID varchar2(12) NOT NULL,
	NAME nvarchar2(6) NOT NULL,
	PASSWORD varchar2(16) NOT NULL,
	BIRTH date NOT NULL,
	GENDER char NOT NULL,
	EMAIL varchar2(50) NOT NULL,
	POSTAL_CODE varchar2(10) NOT NULL,
	ADDR_ROAD varchar2(100) NOT NULL,
	ADDR_DETAIL varchar2(100) NOT NULL,
	PROF_IMG_FL char DEFAULT 'N',
	ACTIVE_FL char DEFAULT 'Y',
	REG_DATE date DEFAULT SYSDATE,
	PRIMARY KEY (ID)
);


CREATE TABLE P_IMG
(
	ID varchar2(12) NOT NULL,
	P_LOCATION nvarchar2(100) NOT NULL,
	P_NAME nvarchar2(50) NOT NULL,
	P_EXTENSION varchar2(10) NOT NULL,
	PRIMARY KEY (ID)
);



/* Create Foreign Keys */

ALTER TABLE ATTACH
	ADD FOREIGN KEY (NO)
	REFERENCES BOARD (NO)
;


ALTER TABLE BOOKMARK
	ADD FOREIGN KEY (NO)
	REFERENCES BOARD (NO)
;


ALTER TABLE BOARD
	ADD FOREIGN KEY (ID)
	REFERENCES MEMBER (ID)
;


ALTER TABLE BOOKMARK
	ADD FOREIGN KEY (ID)
	REFERENCES MEMBER (ID)
;


ALTER TABLE INACTIVE
	ADD FOREIGN KEY (ID)
	REFERENCES MEMBER (ID)
;


ALTER TABLE P_IMG
	ADD FOREIGN KEY (ID)
	REFERENCES MEMBER (ID)
;



